export const MODULES_ORDER = [
  "USER",
  "WAREHOUSE",
  "PRODUCT",
  "LC",
  "SALE",
  "CASH",
  "ACCOUNT",
  "TRANSACTION",
  "CUSTOMER",
  "CATEGORY",
  "UNIT",
  "SETTINGS",
  "TRASH",
  "AUDIT",
  "ADVANCE_PAYMENT",
];

/**
 * Frontend mirror of backend BUNDLED_PERMISSIONS.
 * When a permission key is checked, all permissions in its array
 * are auto-checked as prerequisites.
 */
export const PERMISSION_BUNDLES = {
  // CUSTOMER
  CUSTOMER_VIEW_DETAILS: ["CUSTOMER_VIEW_TABLE"],
  CUSTOMER_CREATE: ["CUSTOMER_VIEW_TABLE"],
  CUSTOMER_UPDATE: ["CUSTOMER_VIEW_TABLE", "CUSTOMER_VIEW_DETAILS"],
  CUSTOMER_DELETE: ["CUSTOMER_VIEW_TABLE", "CUSTOMER_VIEW_DETAILS"],

  // SALE
  SALE_VIEW_DETAILS: ["SALE_VIEW_TABLE"],
  SALE_CREATE: ["SALE_VIEW_TABLE"],
  SALE_ADD_PAYMENT: ["SALE_VIEW_TABLE", "SALE_VIEW_DETAILS"],
  SALE_UPDATE: ["SALE_VIEW_TABLE", "SALE_VIEW_DETAILS"],
  SALE_CANCEL: ["SALE_VIEW_TABLE", "SALE_VIEW_DETAILS"],
  SALE_DELETE: ["SALE_VIEW_TABLE", "SALE_VIEW_DETAILS"],

  // LC
  LC_VIEW_DETAILS: ["LC_VIEW_TABLE"],
  LC_CREATE: ["LC_VIEW_TABLE"],
  LC_UPDATE: ["LC_VIEW_TABLE", "LC_VIEW_DETAILS"],
  LC_DELETE: ["LC_VIEW_TABLE", "LC_VIEW_DETAILS"],

  // PRODUCT
  PRODUCT_VIEW_DETAILS: ["PRODUCT_VIEW_TABLE"],
  PRODUCT_CREATE: ["PRODUCT_VIEW_TABLE", "PRODUCT_VIEW_DETAILS"],
  PRODUCT_UPDATE: ["PRODUCT_VIEW_TABLE", "PRODUCT_VIEW_DETAILS"],
  PRODUCT_DELETE: ["PRODUCT_VIEW_TABLE", "PRODUCT_VIEW_DETAILS"],

  // USER
  USER_VIEW_DETAILS: ["USER_VIEW_ALL"],
  USER_CREATE: ["USER_VIEW_ALL"],
  USER_UPDATE: ["USER_VIEW_ALL", "USER_VIEW_DETAILS"],
  USER_DELETE: ["USER_VIEW_ALL", "USER_VIEW_DETAILS"],

  // ACCOUNT
  ACCOUNT_VIEW_DETAILS: ["ACCOUNT_VIEW_ALL"],
  ACCOUNT_CREATE: ["ACCOUNT_VIEW_ALL"],
  ACCOUNT_UPDATE: ["ACCOUNT_VIEW_ALL", "ACCOUNT_VIEW_DETAILS"],
  ACCOUNT_DELETE: ["ACCOUNT_VIEW_ALL", "ACCOUNT_VIEW_DETAILS"],
  ACCOUNT_VIEW_TRANSACTIONS: ["ACCOUNT_VIEW_ALL", "ACCOUNT_VIEW_DETAILS"],

  // TRANSACTION
  TRANSACTION_VIEW_DETAILS: ["TRANSACTION_VIEW_ALL"],
  TRANSACTION_CREATE: ["TRANSACTION_VIEW_ALL"],
  TRANSACTION_UPDATE: ["TRANSACTION_VIEW_ALL", "TRANSACTION_VIEW_DETAILS"],
  TRANSACTION_DELETE: ["TRANSACTION_VIEW_ALL", "TRANSACTION_VIEW_DETAILS"],

  // ADVANCE PAYMENT
  ADVANCE_PAYMENT_VIEW_DETAILS: ["ADVANCE_PAYMENT_VIEW"],
  ADVANCE_PAYMENT_CREATE: ["ADVANCE_PAYMENT_VIEW"],
  ADVANCE_PAYMENT_SETTLE: ["ADVANCE_PAYMENT_VIEW", "ADVANCE_PAYMENT_VIEW_DETAILS"],
  ADVANCE_PAYMENT_REFUND: ["ADVANCE_PAYMENT_VIEW", "ADVANCE_PAYMENT_VIEW_DETAILS"],
  ADVANCE_PAYMENT_DELETE: ["ADVANCE_PAYMENT_VIEW", "ADVANCE_PAYMENT_VIEW_DETAILS"],
};
